steps:
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: "bash"
      args:
        - "-c"
        - |
          echo Response Code is `curl -o /dev/null -s -w "%{http_code}" www.google.com`
options:
    logging: CLOUD_LOGGING_ONLY
